version: 0.0.6.{build}
os: Visual Studio 2015
skip_tags: false
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: JrXjUphTOrdW5JHuMosIgHFT99k0qGDDxw3r+/tV0l3VXUBLDZM57rGNjz8PLJBb
before_build:
- nuget restore
build:
  project: .\vpdb-agent.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" "-targetargs:""C:\projects\vpdb-agent\VpdbAgent.Tests\bin\$env:CONFIGURATION\VpdbAgent.Tests.dll"" /noshadow /appveyor" -returntargetcode -filter:"+[VpdbAgent*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\opencoverCoverage.xml

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID